samples: config/samples.tsv
units: config/units.tsv

ref:
  # ensembl species name
  species: homo_sapiens
  # ensembl release
  release: 98
  # genome build
  build: GRCh38

filtering:
  # Set to true in order to apply machine learning based recalibration of
  # quality scores instead of hard filtering.
  vqsr: true
  hard:
    # hard filtering as outlined in GATK docs
    # (https://gatkforums.broadinstitute.org/gatk/discussion/2806/howto-apply-hard-filters-to-a-call-set)
    snvs:
      "QD < 2.0 || FS > 60.0 || MQ < 40.0 || MQRankSum < -12.5 || ReadPosRankSum < -8.0"
    indels:
      "QD < 2.0 || FS > 200.0 || ReadPosRankSum < -20.0"

processing:
  remove-duplicates: true
  # Uncomment and point to a bed file with, e.g., captured regions if necessary,
  # see https://gatkforums.broadinstitute.org/gatk/discussion/4133/when-should-i-use-l-to-pass-in-a-list-of-intervals.
  # restrict-regions: captured_regions.bed
  # If regions are restricted, uncomment this to enlarge them by the given value in order to include
  # flanking areas.
  # region-padding: 100

#https://gatk.broadinstitute.org/hc/en-us/articles/360057438571--Tool-Documentation-Index
params:
  gatk:
    HaplotypeCaller: " -A QualByDepth -A MappingQualityRankSumTest -A ReadPosRankSumTest -A FisherStrand -A RMSMappingQuality -A StrandOddsRatio -A Coverage"
    BaseRecalibrator: ""
    GenotypeGVCFs: " -A QualByDepth -A MappingQualityRankSumTest -A ReadPosRankSumTest -A FisherStrand -A RMSMappingQuality -A StrandOddsRatio -A Coverage"
    VariantRecalibrator: ""
#    ALL PARAMS ARE HARDCODED INTO THE RULES FOR SNVS AND INDELS
#      --trust-all-polymorphic \
#      -tranche 100.0 -tranche 99.95 -tranche 99.9 -tranche 99.8 -tranche 99.6 -tranche 99.5 -tranche 99.4 -tranche 99.3 -tranche 99.0 -tranche 98.0 -tranche 97.0 -tranche 90.0 \
#       -an QD -an MQRankSum -an ReadPosRankSum -an FS -an MQ -an SOR -an DP \
#       -an AS_QualByDepth -an AS_MappingQualityRankSumTest -an AS_ReadPosRankSumTest -an AS_FisherStrand -an MappingQuality -an AS_StrandOddsRatio -an DepthPerAlleleBySample \
#      -mode SNP \
#      --max-gaussians 6"

  picard:
    MarkDuplicates: "REMOVE_DUPLICATES=true"
  trimmomatic:
    pe:
      trimmer:
        # See trimmomatic manual for adding additional options, e.g. for adapter trimming.
        - "LEADING:3"
        - "TRAILING:3"
        - "SLIDINGWINDOW:4:15"
        - "MINLEN:36"
    se:
      trimmer:
        # See trimmomatic manual for adding additional options, e.g. for adapter trimming.
        - "LEADING:3"
        - "TRAILING:3"
        - "SLIDINGWINDOW:4:15"
        - "MINLEN:36"
  vep:
    plugins:
      # Add any plugin from https://www.ensembl.org/info/docs/tools/vep/script/vep_plugins.html
      # Plugin args can be passed as well, e.g. "LoFtool,path/to/custom/scores.txt".
      - LoFtool
    # extra command line arguments (e.g. --sift, see docs)
    extra: "–hgvsg"
